apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: argocd-rules
  namespace: monitoring
spec:
  groups:
  - name: argocd.health
    rules:
    - alert: ArgoCDDown
      expr: up{namespace="argocd",job="argocd-server"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Argo CD API is unreachable"
        description: "No healthy Argo CD server pods for >2m"
