apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomkid21/gitops-demo.git
    targetRevision: main
    path: apps/guestbook-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
