spec:
  template:
    spec:
      initContainers:
        - name: fetch-custom-helm
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - mkdir -p /custom-helm && curl -sSL https://get.helm.sh/helm-v3.10.0-linux-amd64.tar.gz | tar -xz -C /custom-helm linux-amd64/helm --strip-components=1 && chmod +x /custom-helm/helm
          volumeMounts:
            - name: custom-helm
              mountPath: /custom-helm
      volumes:
        - name: custom-helm
          emptyDir: {}
      containers:
        - name: argocd-repo-server
          command:
            - /custom-helm/helm
            - repo
            - serve
          volumeMounts:
            - name: custom-helm
              mountPath: /custom-helm
