apiVersion: apps/v1
kind: Deployment
metadata:
  name: kps-grafana
  namespace: monitoring
spec:
  template:
    spec:
      volumes:
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
      containers:
        - name: grafana
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
